server:
  port: 18082
spring:
  application:
    name: forum-user
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/forum_spring_db?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      max-wait: 10000
      min-evictable-idle-time-millis: 600000
      max-evictable-idle-time-millis: 900000
      time-between-eviction-runs-millis: 60000
      keep-alive: true
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deletedOn
      logic-delete-value: now()
      logic-not-delete-value: 'null'