server:
  port: 18086
spring:
  application:
    name: forum-search
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
meilisearch:
  host-url: http://localhost:7700
  api-key: api-key