apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-deployment
  namespace: ns-forum
  labels:
    app: search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
        - name: search
          image: docker.io/cbluebird/forum-search:v0.0.7
          volumeMounts:
            - name: config
              mountPath: /app/application.yaml
              subPath: application.yaml
              readOnly: true
            - name: log-config
              mountPath: /app/logback-spring.xml
              subPath: logback-spring.xml
              readOnly: true
          ports:
            - containerPort: 18086
      volumes:
        - name: config
          configMap:
            name: search-config
            items:
              - key: application.yaml
                path: application.yaml
        - name: log-config
          configMap:
            name: log-config
            items:
              - key: logback-spring.xml
                path: logback-spring.xml

---
apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: ns-forum
  labels:
    app: search
spec:
  selector:
    app: search
  ports:
    - protocol: TCP
      port: 18086
      targetPort: 18086